const todos = require("../controllers/note.controller.js");
const users = require("../controllers/user.controller.js");
const router = require("express").Router();
router.post("/note", todos.createNote);
router.get("/note", todos.findAllNotes);
router.get("/note/:title", todos.findNote);
router.delete("/note/:id", todos.deleteNote);
router.post("/register", users.register);
router.post("/login", users.login);
module.exports = router;